In [1]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   str
 3   item_purchased          3900 non-null   str
 4   category                3900 non-null   str
 5   purchase_amount_(usd)   3900 non-null   int64
 6   location                3900 non-null   str
 7   size                    3900 non-null   str
 8   color                   3900 non-null   str
 9   season                  3900 non-null   str
 10  review_rating           3863 non-null   float64
 11  subscription_status     3900 non-null   str
 12  shipping_type           3900 non-null   str
 13  discount_applied        3900 non-null   str
 14  promo_code_used         3900 non-null   str
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   str
 17  frequency_of_purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [5]:
df.describe(include = 'all')

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_(usd)      0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

KeyError: 'Category'

In [8]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_(usd)      0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df =df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [12]:
#create a age group 
labels = ['Young Adult','Adult','Middel-aged','Senior']
df['age_group'] =pd.qcut(df['age'],q=4,labels =labels)

In [13]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middel-aged
1   19  Young Adult
2   50  Middel-aged
3   21  Young Adult
4   45  Middel-aged
5   46  Middel-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middel-aged

In [14]:
#create column purcahse_frequency_days
frequency_mapping = {'Fortnightly':14,
                     'Weekly':7,
                     'Monthly':30,
                     'Quarterly':90,
                     'Bi-Weekly':14,
                     'Annually':365,
                     'Every 3 Months':90}
df['purchase_frequency_days'] =df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [16]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [17]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [19]:
df. columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [20]:
for col in df.columns:
    print(repr(col))

'customer_id'
'age'
'gender'
'item_purchased'
'category'
'purchase_amount'
'location'
'size'
'color'
'season'
'review_rating'
'subscription_status'
'shipping_type'
'discount_applied'
'promo_code_used'
'previous_purchases'
'payment_method'
'frequency_of_purchases'
'age_group'
'purchase_frequency_days'

In [21]:
df.columns = df.columns.str.strip().str.lower()

df.to_sql(
    "customer_behavior",
    engine,
    if_exists="replace",   # Replaces the old table
    index=False
)

print("Table updated successfully!")

NameError: name 'engine' is not defined

In [22]:
print("promo_code_used" in df.columns)

True

In [23]:
import sys
print(sys.version)

3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]

In [24]:
!python -m pip install psycopg[binary] sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\tanu kailash kamble\appdata\roaming\python\python313\site-packages (2.0.51)
Requirement already satisfied: psycopg[binary] in c:\users\tanu kailash kamble\appdata\roaming\python\python313\site-packages (3.3.4)
Requirement already satisfied: tzdata in c:\users\tanu kailash kamble\appdata\roaming\python\python313\site-packages (from psycopg[binary]) (2026.2)
Requirement already satisfied: psycopg-binary==3.3.4 in c:\users\tanu kailash kamble\appdata\roaming\python\python313\site-packages (from psycopg[binary]) (3.3.4)
Requirement already satisfied: greenlet>=1 in c:\users\tanu kailash kamble\appdata\roaming\python\python313\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\tanu kailash kamble\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("Tanu@123")   # Your PostgreSQL password
host = "localhost"
port = "5432"
database = "postgres"

engine = create_engine(
    f"postgresql+psycopg://{username}:{password}@{host}:{port}/{database}"
)

conn = engine.connect()

print("✅ Connected Successfully!")

In [26]:
import pandas as pd

df = pd.read_sql("SELECT version();", conn)
df

NameError: name 'conn' is not defined

In [27]:
pd.read_sql("""
SELECT datname
FROM pg_database;
""", conn)

NameError: name 'conn' is not defined

In [28]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("Tanu@123")
host = "localhost"
port = "5432"
database = "customer_behavior"   # Change this

engine = create_engine(
    f"postgresql+psycopg://{username}:{password}@{host}:{port}/{database}"
)

conn = engine.connect()
print("✅ Connected to customer_behavior")

OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
Multiple connection attempts failed. All failures were:
- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [29]:
import pandas as pd

pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';
""", conn)

NameError: name 'conn' is not defined

In [30]:
pd.read_sql("""
SELECT schemaname, tablename
FROM pg_tables;
""", conn)

NameError: name 'conn' is not defined

In [31]:
pd.read_sql("SELECT current_database();", conn)

NameError: name 'conn' is not defined

In [32]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("ALTER USER postgres WITH PASSWORD 'Tanu@123';"))

print("Password reset successfully")

OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
Multiple connection attempts failed. All failures were:
- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [33]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("ALTER USER postgres WITH PASSWORD 'Tanu123';"))

print("Password changed to Tanu123")

OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
Multiple connection attempts failed. All failures were:
- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [34]:
pd.read_sql("SELECT inet_server_addr(), inet_server_port(), current_user, current_database();", conn)

NameError: name 'conn' is not defined

In [35]:
pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';
""", conn)

NameError: name 'conn' is not defined

In [36]:
from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("""
    INSERT INTO customers VALUES
    (1, 'Tanu', 23, 'Nagpur'),
    (2, 'Amit', 25, 'Pune'),
    (3, 'Priya', 22, 'Mumbai');
    """))

print("Data inserted")

OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
Multiple connection attempts failed. All failures were:
- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [37]:
pd.read_sql("SELECT * FROM customers;", conn)

NameError: name 'conn' is not defined

In [38]:
import os

downloads = r"C:\Users\Tanu Kailash Kamble\Downloads"

for file in os.listdir(downloads):
    if file.endswith(".csv"):
        print(file)

airline_route_profitability_1200_rows.csv
amazon.csv
Claims.csv
customer_shopping_behavior.csv
data_cleaning_practice_dataset.csv
Date.csv
finance sql.csv
googleplaystore (1).csv
googleplaystore (2).csv
googleplaystore.csv
Hospital_Data.csv
indian_roads_dataset.csv
Item.csv
Location.csv
messy_dataset_5000_rows.csv
Payment.csv
Payments.csv
perishable_goods_management.csv
pizza_sales.csv
Policies.csv
Sales.csv
samplesuperstore (1).csv
samplesuperstore.csv
sql file.csv
student.csv
test.csv

In [39]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Tanu Kailash Kamble\Downloads\customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [40]:
df.to_sql(
    "customer_behavior",
    engine,
    if_exists="replace",
    index=False
)

print("✅ Data imported successfully!")

OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
Multiple connection attempts failed. All failures were:
- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [41]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import pandas as pd

password = quote_plus("Tanu123")   # try this

engine = create_engine(
    f"postgresql+psycopg://postgres:{password}@localhost:5432/customer_behavior"
)

conn = engine.connect()

print("Connected again")

Connected again

In [42]:
pd.read_sql("SELECT current_database(), current_user;", conn)

    current_database current_user
0  customer_behavior     postgres

In [43]:
pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';
""", conn)

              table_name
0              customers
1      customer_behavior
2  customer_behavior_new

In [44]:
pd.read_sql("SELECT * FROM customer_behavior LIMIT 5;", conn)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [45]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

df.to_sql(
    "customer_behavior_new",
    engine,
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi"
)

print("Updated table saved successfully")

Updated table saved successfully

In [47]:
pd.read_sql("SELECT * FROM customer_behavior_new LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [50]:
conn.close()

In [51]:
conn.close()
engine.dispose()

print("Jupyter database connections closed")

Jupyter database connections closed